# Generated by Django 2.2.6 on 2019-10-22 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='images/', verbose_name='画像')),
                ('title', models.CharField(max_length=30, verbose_name='名前（フルネーム、漢字、空白なし）')),
            ],
            options={
                'verbose_name_plural': 'メンバー画像',
                'db_table': 'image',
            },
        ),
    ]
