# Generated by Django 2.2.6 on 2019-10-22 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nogidb', '0002_auto_20191022_1106'),
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nogidb.Member'),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=30, verbose_name='名前（フルネーム・漢字・空白なし'),
        ),
    ]
