# Generated by Django 2.2.6 on 2019-10-22 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_auto_20191022_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nogidb.Member'),
        ),
    ]
