# Generated by Django 2.2.6 on 2019-10-22 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_auto_20191022_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nogidb.Member', verbose_name='名前'),
        ),
    ]
