# Generated by Django 2.2.6 on 2019-10-20 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名前')),
                ('name_kana', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='「名前（かな）」は、ひらがな・カタカナのみで空白を入れずに入力してください', regex='^[ぁ-んァ-ヶ]+$')], verbose_name='名前（かな）')),
                ('birthday', models.DateField(verbose_name='生年月日')),
                ('join_class', models.PositiveIntegerField(choices=[(1, '1期生'), (2, '2期生'), (3, '3期生'), (4, '4期生')], verbose_name='加入時期')),
                ('status', models.PositiveIntegerField(choices=[(0, '現役'), (1, '卒業生')], verbose_name='活動状態')),
            ],
            options={
                'verbose_name': 'メンバー',
                'db_table': 'member',
            },
        ),
    ]
