# Generated by Django 2.2.6 on 2019-10-22 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nogidb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name_plural': 'メンバー'},
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, '活動中'), (1, '卒業生')], verbose_name='活動状況'),
        ),
    ]
